services:
  phone1:
    image: hydra/redroid:14.0.0-hydra
    container_name: phone1
    privileged: true
    volumes:
      - phone1-data:/data
    ports:
      - "5555:5555"
    command:
      - androidboot.use_memfd=true
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_dpi=320
      - androidboot.redroid_fps=30
      - androidboot.redroid_gpu_mode=guest
      - ro.setupwizard.mode=DISABLED

volumes:
  phone1-data:
